### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by Roymprog** [sfu-db/connector-x#483]
#### Python 3.11 support

Please release a new stable version of the package, so `connectorx` can be used with python3.11. 
The [two latest prerelease versions](https://pypi.org/project/connectorx/0.3.2a2/#files) are built for python 3.11.

**Comment by sslivkoff** [comment]
it would be helpful to have a more frequent release schedule, even if they are relatively minor updates

**Comment by owenlamont** [comment]
I'd like that too, is there much else to do on the 0.3.2 release before that goes stable?

**Comment by DeflateAwning** [comment]
Please release `connectorx==0.3.1` for Python 3.11. Seems like an oversight that it wasn't released like that in the first place.

**Comment by fdcastel** [comment]
@anyone?

There's anything blocking this (apparently very simple to fix, but causing major issues to users) issue?

**Comment by rafmagns-skepa-dreag** [comment]
Bumping this. Did some searching around in the issues and PRs and haven't found anything that seems to be blocking either a 0.3.2 release or building a 3.11 wheel. Are there plans to create a new release in the near future?

**Comment by RmStorm** [comment]
I hope one of the maintainers makes a new release sometime soon :tm: but untill then it is possible to use a pre-release that does have proper python 3.11 wheels like so:
`poetry add connectorx==0.3.2a7` or `pip install connectorx==0.3.2a7`
As of this writing there is 7 pre-releases for 0.3.2 I haven't read the release notes, YOLO, just going with number 7 since it works :smile:.

**Comment by evbo** [comment]
@RmStorm on Centos7.9 I can't install the latest pre-release:

> pip install connectorx==0.3.2a7 --pre
ERROR: Could not find a version that satisfies the requirement connectorx==0.3.2a7 (from versions: 0.2.3, 0.3.2a1, 0.3.2a2)
ERROR: No matching distribution found for connectorx==0.3.2a7

This is using pip 23.2.1 on python 3.11.... any suggestions?

**Comment by wangxiaoying** [comment]
Hi @RmStorm  We just released a stable version `0.3.2`. Please feel free to check out.

**Comment by ilyanoskov** [comment]
Is there any chance you can enable support for Python >= 3.11.3 ? Right now it does not work

**Comment by jensenbox** [comment]
Using Python 3.11.6 I am getting this:

![image](https://github.com/sfu-db/connector-x/assets/189265/f864a96d-5327-4015-841a-703f02eebee3)

**Comment by DeflateAwning** [comment]
This is crazy that this is still an issue. Do any maintainers know what the problem/hold-up is?

**Comment by Cayan** [comment]
Pre-release 0.3.2a7 didn't work for me

```
Unable to find installation candidates for connectorx (0.3.2a7)
```

**Comment by Cayan** [comment]
The latest pre-release `0.3.3a1 didn't work either

```
poetry add connectorx --allow-prereleases
```

**Comment by wangxiaoying** [comment]
<img width="1021" alt="image" src="https://github.com/sfu-db/connector-x/assets/5569610/3ffd7076-0815-4d85-9919-ea85a71b8b5f">

We support python 3.11 since latest stable version: `0.3.2`. I will close this issue for now. Please feel free to reopen if you find any issue.

**Comment by wonb168** [comment]
mac is ok，but cannot in centos7，py311
